name: EconXPIntegrator
author: Faw
version: 1.0.0
main: me.bottleofglass.econxpintegrator.Main
depend: [Vault, CMI]
commands:
  econlogs:
    usage: "Usage: /econlogs enable/disable"
    description: enables player logs

