name: EconXPIntegrator
author: Faw
version: 1.0.0
main: me.bottleofglass.econxpintegrator.Main
depend: [Vault, CMI]
commands:
  econlogs:
    description: enables player logs
    usage: "Usage: /econlogs enable/disable"
permissions:
  #expecon.xppercentage.<1-100>
  expecon.xppercentage.*:
    description: Indicates the percentage of experience kept on death
    default: false
